### ISSUE TITLE
Can these be turned into a variant of Netherite gear?

### ISSUE THREAD

**Issue by Lxndwich** [xVemu/diamold#9]
It'd be super cool to have something like "Golderite" (name made by me) added to the mod, which has the same efficiency as Gold with the durability and fire-proof quality of Netherite.

Oh, and I'm also curious if this doesn't just add Gold's efficiency, but its enchantability as well. If Diamold tools/armor don't have its enchantability, then "Golderite" should.

If you do consider adding this, can you add it to every version 1.16 and above? That'd be super cool.

**Comment by xVemu** [comment]
> It'd be super cool to have something like "Golderite" (name made by me) added to the mod, which has the same efficiency as Gold with the durability and fire-proof quality of Netherite.

That's a great idea. Surely I will add this.
> Oh, and I'm also curious if this doesn't just add Gold's efficiency, but its enchantability as well. If Diamold tools/armor don't have its enchantability, then "Golderite" should.

Yes, diamold tools have the same enchantability as gold tools.
> If you do consider adding this, can you add it to every version 1.16 and above? That'd be super cool.

Thanks for the suggestion. I'm going to add Golderite in a month or two and try to make it to every version 1.16+ as you said.

**Comment by xVemu** [comment]
Sorry, but I don't think I could make this in the near feature.
